security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        auth0:
            id: App\Security\UserProvider

    firewalls:
        main:
            pattern:            ^/
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
                default_target_path: admin_dashboard
                always_use_default_target_path: true
            logout:
                path:           fos_user_security_logout
                target:         fos_user_security_login
            anonymous:          true
            oauth:
              resource_owners:
                google: "/login/check-google"
                facebook: "/login/check-facebook"
              login_path: fos_user_security_login
              failure_path: fos_user_security_login
              oauth_user_provider:
                service: AppBundle\Provider\FOSUBUserProvider

    access_control:
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^//resetting/(.*), role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(.*), role: ROLE_ADMIN }
    - { path: ^/admin/(.*), role: ROLE_SUPER_ADMIN }

